### ISSUE TITLE
[Self-Managed]: Unable to upgrade 7.16.2 Snapshot Fleet-Server to 8.0 Snapshot on upgraded 8.0 Snapshot Kibana.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#1037]
**Kibana version:**  7.16.2>8.0.0 Snapshot Upgraded Kibana self-managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
Build: 48868
Commit: a29e0164a4af4d3135910cac9e6caa4478af5f3b
Artifact Link 7.16.2 agent: https://snapshots.elastic.co/7.16.2-02e7fd8e/downloads/beats/elastic-agent/elastic-agent-7.16.2-SNAPSHOT-windows-x86_64.zip
```

**Preconditions:**
1.  7.16.2>8.0.0 Snapshot Upgraded Kibana self-managed environment should be available.
2. 7.16.2 Snapshot fleet server should be installed with Default Fleet Server policy with System, Endpoint and Fleet Server integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Trigger fleet server upgrade from Fleet UI.
3. Observe Fleet Server stucks in `Upgrading` state.
4. Observe two folders created under `Elastic\Agent\data`.

**Logs:**

[elastic-agent-3c518f-logs.zip](https://github.com/elastic/fleet-server/files/7783451/elastic-agent-3c518f-logs.zip)
[elastic-agent-20211228.zip](https://github.com/elastic/fleet-server/files/7783454/elastic-agent-20211228.zip)

**Endpoint logs:**
[log.zip](https://github.com/elastic/fleet-server/files/7783420/log.zip)

**Expected Result:**
7.16.2 Snapshot Fleet-Server should upgrade to 8.0 Snapshot on upgraded 8.0 Self-managed snapshot kibana

**Screenshots:**

![1](https://user-images.githubusercontent.com/77374876/147541138-d136e692-2591-4da0-97c0-05f41bf988b1.JPG)

![2](https://user-images.githubusercontent.com/77374876/147541145-a1802dd7-eaec-4ad7-848b-0682b021897f.JPG)

**Note:**
- This issue is observed for fleet server stuck in updating from 02 hours.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @elastic/elastic-agent-control-plane

**Comment by jlind23** [comment]
Hey there, after looking at the logs I do see two different issues and both can be found in this zip elastic-agent-20211228.zip.
The first one is a failed deletion caused by endpoint:
`Application: endpoint-security--8.0.0-SNAPSHOT[456ee4e4-5bf8-4ce7-aba5-397636d8b8c3]: State changed to FAILED: operation 'Exec' failed (return code: 5): 2021-12-28 05:29:52: info: Main.cpp:356 Upgrading existing installation (protected)\r\n2021-12-28 05:29:52: info: InstallLib.cpp:476 Attempting to create a rollback package\r\n2021-12-28 05:29:54: info: InstallLib.cpp:315 Running [c:\\program files\\elastic\\agent\\data\\elastic-agent-5ae676\\install\\endpoint-security-8.0.0-snapshot-windows-x86_64previouselastic-endpoint.exe] [uninstall --rollback --log stdout]\r\n2021-12-28 05:29:59: info: InstallLib.cpp:334 Upgrade helper succeeded with output 2021-12-28 05:29:56: info: Main.cpp:306 Executing uninstall with rollback\r\r\n2021-12-28 05:29:56: debug: File.cpp:479 Removing [C:\\Program Files\\Elastic\\Endpoint\\elastic-endpoint.yaml]\r\r\n2021-12-28 05:29:56: info: File.cpp:509 Attempted deletion failed, failed to reset file attributes for C:\\Program Files\\Elastic\\Endpoint\\elastic-endpoint.yaml\r\r\n2021-12-28 05:29:56: debug: Internal.cpp:472 Removal of C:\\Program Files\\Elastic\\Endpoint\\elastic-endpoint.yaml failed while creating rollback archive.\r\r\n2021-12-28 05:29:56:`
@andrewkroh what does (protected) means here? Can it be related to some specific permissions issue?

The second one is linked to metricbeat and a file not found:
`'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5ae676\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip' not found: open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5ae676\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip` 

@amolnater-qasource is the metricbeat archive available locally?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
Thanks for looking into this, we have attempted to revalidate this issue.
Today we are successfully able upgrade 7.16.2 snapshot agent to 8.0 Snapshot on upgraded 8.0 Snapshot kibana. 

**Screenshot:**
![16](https://user-images.githubusercontent.com/77374876/148202148-8f257a5c-9aaa-4031-a349-0e63e05b882f.JPG)

Hence we are **closing** this issue.
Further we will keep track of this, if found reproducible in future.
Thanks
