### ISSUE TITLE
Ensure GZIP responses are returned from HTTP endpoint

### ISSUE THREAD

**Issue by blakerouse** [elastic/fleet-server#108]
From elastic/integrations#729 we need to ensure that Fleet Server is returning gzipped compressed responses to the Elastic Agent.

**Comment by scunningham** [comment]
This is going to be resource intensive. Which part are we worried about getting too big?

**Comment by ruflin** [comment]
The problem are that some policies are pretty large as they have (too much) js lookup tables inside. We should make this feature configurable.

One issue I see is that we have to gzip it for every agent as each policy is a bit different because of the API keys? This means we also can't do it once and ship the same to all agents?

**Comment by scunningham** [comment]
I am concerned about payload size too.  Supporting compression at the http level is the simplest solution.  I'm not sure we have a choice without significantly changing how the payload is structured because when inject data into the policy.

Best we can do is support the cheapest/fastest compression we can get away with.  Either zlib.BestSpeed or lz4 is better if the agent supports it.  This will impose some CPU load on the Fleet Server at policy change time.  We should probably only compress if the response to the agent is beyond a minimal threshold.

**Comment by ruflin** [comment]
@leehinman @ycombinator For visibility as you were involved in https://github.com/elastic/integrations/issues/729 ^
