### ISSUE TITLE
Provide scaling guidance for Fleet server on cloud

### ISSUE THREAD

**Issue by mostlyjason** [elastic/fleet-server#134]
We'd like to provide updated scaling guidance for the new Fleet server on ESS. We currently publish scaling guidance to help users determine how many agents they can realistically expect to enroll into a given instance size for the hosted agent on cloud https://www.elastic.co/guide/en/fleet/current/fleet-limitations.html. This was based on Kibana so we should update it for Fleet Server.

We should identify how many agents can be enrolled into the APM & Fleet slider at each increment of memory up to the max node memory size (8GB). This will help the user identify how to set the connection limit in the Fleet Server integration policy. https://github.com/elastic/fleet-server/issues/153 

I think we also need to make some assumptions about workload when giving our guidance. Fleet server is now bundled with APM server on the same instance, but not all users of Fleet server will necessarily be using APM server. I think it'd be more clear to assume minimal or no APM usage beyond the baseline, so we can isolate the requirements for Fleet Server capacity. The resource needs may also vary between the initial ramp up of enrolling agents and the steady state load of check ins once the agents are enrolled. We should at least cover the check in load requirements when setting a max.

Resource usage may vary in real world scenarios, so we'll also provide observability into resource usage to help users know when to scale their slider once in production.

Stretch goal:
- Guidance on whether the user should scale ES nodes to handle increased search traffic

Related discussions: 
- Fleet server scale testing https://github.com/elastic/fleet-server/issues/95
- Instance type for cloud https://github.com/elastic/cloud/issues/72128
- Resource usage in one container https://github.com/elastic/obs-dc-team/issues/470

**Comment by mostlyjason** [comment]
I spoke with @scunningham and he's going to do some scale testing on cloud to get initial numbers. One concern is that APM is a GA release and users may not anticipate that they need to scale their instance just because Fleet server is included, even if they are not using it. Ideally, a default slider with 512 MB could handle a full load for APM traffic and a small load for Fleet Server. During the beta, a significant percentage of clusters have fewer than 10 agents enrolled. Can we make that fit?

**Comment by simitt** [comment]
I am setting up an ECE instance allowing us to run some tests with APM and Elastic Agent/Fleet Server enabled.

**Comment by bradenlpreston** [comment]
@scunningham - FYI.

**Comment by EricDavisX** [comment]
@mostlyjason do you mind if we extend this to providing scale guidance not just for cloud but also self-managed clusters?  or is that implied already? :)  I can spin a new ticket if you prefer.

**Comment by mostlyjason** [comment]
@EricDavisX I'm wondering if it would be useful for self-managed clusters given there so much diversity in hardware configurations. Have you seen other Elastic products offer this guidance for self-managed clusters?

**Comment by EricDavisX** [comment]
@mostlyjason  I have not seen any, good to call that out.  The Fleet Server use case is new to Elastic, so prior products (with the exception of ES itself) may not have had the 100k + scale of concurrent connections.   I suppose it is from my prior experience with Elastic Endgame support where security customers seem to desire some minimum expectation (which helps the product team too, to identify minimum configurations to test with and which we can expect to work).  

I don't find the diversity of hardware available to be preventative of picking some representative or 'common' configuration for a given use case and citing expectations based on that.  I think user's would want it.  

If the cloud guidance is somewhat directly relatable to on-prem scaling it may totally fulfill the need, too (Linux containers are a solid reference point perhaps).  Just calling out that customers likely will want it to scale Endpoint and Agent deploys, on prem as well as cloud.

**Comment by mostlyjason** [comment]
@EricDavisX makes sense! Can you create a separate issue for that so we can schedule it independently? I'd focus on cloud first since we are responsible for giving guidance, and we probably don't want users running arbitrary scale tests.

**Comment by scunningham** [comment]
We will be tracking data in [google spreadsheet](https://docs.google.com/spreadsheets/d/115Ch1U1PWoglliYptgDKsXo003akBsN5tdAbLXUVuV8/edit?ts=60ddbc67#gid=0).

# Methodology

We will attempt to qualify the number of support endpoints per configuration, both on prem and in the cloud.  For each class of hardware, we will determine the number of endpoints that Fleet can handle under the following scenarios:

1) Enrollment:  How many endpoints can the system support at fixed rate up to 50/s.

2) Policy change normal: Roll out new policy every 1 minute for 5 minutes and measure time when last policy has been rolled out to all agents.  Security plugin will be enabled to test artifact delivery.

3) Policy change edge: Halt the horde.  Update the revision onthe defaul policy.  Redeploy the horde.  Measure the amount of time it takes for the policy to roll out to all agents. Security plugin will be enabled to test artifact delivery.

4) Action rollout / response (TBD)


ElasticSearch clustesrs will be create in RAM 32x proprotion to the size of the Fleet Server allocation.  So if the RAM allocated for Fleet Server/APM in total is 1 GB, the Elastic Cluster will be roughly 32 GB total.

The default configuration for cloud is specifically for the smalles 512MB container.  To accomodate higher scales, the configuration must be changed in the Fleet Server intergration.  The employed configuration for each tier will be included in the spreadsheet.


Notes:  We have seen issues with ApiKey authentication in Elastic Search.  There is a cache in ES that improves authorization performance, but it is too small for the large deployments (ie. > 12.5k).  The size of the cache is configurable on-prem, but is not accessible in the cloud.  We will leave the configuration size untouched for this test.

## Details

1) Stand up Horde.  See notes in https://github.com/elastic/horde.  You will need a large enough horde to accomodate the largest fleet to be tested; the recommendatiaon is to over provision horde instead of under provision; otherwise you are testing horde as well as the fleet-server.

2) Create cluster in [staging](https://staging.found.no/deployments) or [qa](https://console.qa.cld.elstc.co/deployments) cloud environments.  In most cases, you will want to create the cluster in the same zone as the horde to avoid cross zone costs.  (unless you are testing cross zone).  Pay attention to the stack packed used to create the cluster, in our case we are using 7.14-snapshot.  Tweak both the size of the cluster and the size of the fleet/apm server to whatever combination you are trying to test.

3) Once the cluster is created, navigate to the Fleet page and adjust the Fleet configuration specified in the "Elastic Agent Cloud Policy". 

4) Add the security plugin to the "Default Policy" to help exercise artifact retrieval in the endpoint.

5) Use the specified credentials in the "Add Agent" dialog to "enroll" the emulated agents in horde:
  
  For example:
  `
  enroll -rate 76 40k https://b1c2f81ad19d4a56931a38674fd911db.fleet.us-central1.gcp.qa.cld.elstc.co:443 Um1QU29Ib0JNX2lzTWFhRFB0eVo6SlktX0pnQmdRNnFBTjdPZW0zelVkdw==
  `

6) Once the horde has completely enrolled, run test 2 and test 3 above.

7) Halt the horde and tear down the clusters.
 

While testing for policy rollout, can you use the following snippet in dev tools.  You will have to replace the "policy_id" with the policy_id corresponding to "Default Policy" in your cluster.

To test for policy version up date date use:

```
GET /.fleet-agents/_search
{
  "size": 0,
  "query": {
     "term": {
       "policy_id": "f707b400-de71-11eb-adc8-556a698911e7"
     }
  },
  "aggs": {
    "versions": {
      "terms": {
        "field": "policy_revision_idx"
      }
    }
   }
}

```

Similary, to remove agent records to restart a test on a specific policy_id:

```
POST .fleet-agents/_delete_by_query?conflicts=proceed
{
  "query": {
    "term": {
      "policy_id": "f707b400-de71-11eb-adc8-556a698911e7"
    }
  }
}

```

**Comment by mostlyjason** [comment]
Awesome thanks @scunningham let us know when the numbers are final so we can update the docs

**Comment by scunningham** [comment]
@michalpristas will finish this testing.

**Comment by nimarezainia** [comment]
The document is under review. We will add the details that we have to our public docs.
