### ISSUE TITLE
Can we get rid of Fleet Server max agent config option?

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#1860]
Today, in order to set up fleet server config, we ask user to type the max number of Elastic Agent they are going to run on their deployment by using the Fleet ui.

Based on this number, we generate fleet server config based on the files available in this [folder](https://github.com/elastic/fleet-server/tree/main/internal/pkg/config/defaults).

The question is - Can we get rid of this option and rather let fleet server discovering its environment (Memory available, CPU, ..) and figuring out what the best configuration will be based on this discovery instead of asking the user to set this up.

@blakerouse @michalpristas @scunningham @kpollich  @michel-laterman @nimarezainia @cmacknz  What are your thoughts on this? Any reason why we need to keep this config?

cc @joshdover @jen-huang @pierrehilbert

**Comment by scunningham** [comment]
This would be much simpler if we were in a dedicated container rather than one of N processes running in an integration container.  As it is, it is not clear what percentage of the resources we are allowed to use, and whether that should be a fixed percentage or a running average.  The Fleet Server is very bursty; under normal circumstances its CPU usage is minimal but under load it can be quite heavy in both CPU and RAM.

Nonetheless, assuming we are running in our cloud environment, it would make some sense to do this dynamically given agreement on the proportion of resources dedicated to the Fleet Server.  Could make sense in a customer environment as well, assuming the customer is given visibility into what was selected as well as the capability to override, which is currently broken.

Customer would need to understand given the size/count of integration servers they have selected, how many agents this supports.  It is currently not very clear when folks are setting up their clusters.

**Comment by jlind23** [comment]
> Customer would need to understand given the size/count of integration servers they have selected, how many agents this supports. It is currently not very clear when folks are setting up their clusters.

With the recommended config that we are documenting with all the performance testing we are doing, wouldn't that be enough?

**Comment by scunningham** [comment]
Ideally the customer would not have to delve through pages of documentation when trying to setup their cluster in the cloud UX to determine this.  If we know for an integration server cluster configuration how many agents it would support, ideally that number would be visible in the UX.  

The documentation will certainly be very helpful to folks standing up their own systems.

**Comment by michel-laterman** [comment]
Wasn't the `max_agent` config added to simplify the custom yaml needed to increase the limits? 
If we wanted to remove it we would need to ensure that on-prem instances are simple to configure.

**Comment by joshdover** [comment]
> This would be much simpler if we were in a dedicated container rather than one of N processes running in an integration container.

This is a really important point. Especially if we're going to consider adding any other processes to this container in the short-term (which I'd still prefer to avoid), we'll need some way to artificially and intelligently throttle each process. Currently, the max agents setting is serving this purpose. I don't think with our current cloud architecture that we can start making assumptions that the entire container is for Fleet Server capacity.

Unforuntately, I think we need to keep this around in the meantime until we have a more proper single-purpose container for Fleet Server.

**Comment by jlind23** [comment]
After discussing with @joshdover we will close this issue and rather work on adding more presets files inside the fleet server repository.
https://github.com/elastic/fleet-server/tree/main/internal/pkg/config/defaults
