### ISSUE TITLE
Make Fleet spaces aware

### ISSUE THREAD

**Issue by zez3** [elastic/fleet-server#2075]
There was this discussion here:
https://discuss.elastic.co/t/elastic-agent-fleet/254691

Also my other issue https://github.com/elastic/kibana/issues/132559 that I suppose it can be moved or closed as long as this one will get a team assigned

and an Internal  ER number 17456

**Comment by nicpenning** [comment]
Should a new issue be created for Role Based Access Control for Fleet? Or this one renamed to better align with the actual need here for logically separating access to Fleet components (integrations, policies, agents, etc..).

**Comment by jlind23** [comment]
@nicpenning I don't think a new issue is needed as it will greatly overlap with the intent of this one.

**Comment by nicpenning** [comment]
Looking for an update here on RBAC for Fleet. Is this in the works? Being tracked elsewhere?

**Comment by zez3** [comment]
@jamiehynds 
Any updates on this?

**Comment by zez3** [comment]
My sysadmin colleagues are asking for this feature more, than ever. They want to control the updates of the Agents themself.
I don't want to create a workaround that will be obsolete soon. I just need to know that it's happening and get an idea of about when.

**Comment by nimarezainia** [comment]
> @nimarezainia
> 
> My sysadmin colleagues are asking for this feature more, than ever. They want to control the updates of the Agents themself. I don't want to create a workaround that will be obsolete soon. I just need to know that it's happening and get an idea of about when.

@zez3 and @nicpenning we are working on making Fleet space aware, this is one of the higher priority features under consideration at the moment.
So that roles within one space don't have access to another (eg. one space won't be able to read or make changes to agent policies (and by extension agents) that belong to a different space, they won't be able to see other spaces' enrollment tokens, they will only be able to perform Fleet actions such as upgrades to agents/policies in their own space etc). We won't be considering space awareness for ingest pipelines or datastreams with these changes. 

A question for you on this topic: I'm somewhat familiar with each of your environments. If fleet was made to be space aware, how should we treat the Fleet-->Settings tab in your opinion? changes here are global and would affect all the users on the platform. Would you consider an admin (super user role type) to be the persona that has read/write access to these global settings tab and the only role that could add outputs, modify fleet-server settings and add proxies? Other roles (in the context of their own space) could then modify their agent policy to use global settings such as a new output created.

**Comment by nicpenning** [comment]
I can see where Fleet Settings would simply be disabled/hidden for users that don't have the super user or appropriate user access to perform that action.

Also, I think it's okay that ingest pipelines and data streams need not be space aware, I can't think of any use case where that would be needed. 

The biggest thing right now is server admins managing server agents vs endpoint admins managing endpoint agents and SOC managing all,  some or none of those and other key agents. Doing this via spaces seems logical as they would have their own view of what can be managed.

**Comment by zez3** [comment]
>A question for you on this topic: I'm somewhat familiar with each of your environments. If fleet was made to be space aware, how should we treat the Fleet-->Settings tab in your opinion? changes here are global and would affect all the users on the platform. Would you consider an admin (super user role type) to be the persona that has read/write access to these global settings tab and the only role that could add outputs, modify fleet-server settings and add proxies? Other roles (in the context of their own space) could then modify their agent policy to use global settings such as a new output created.

That sounds about right. The Fleet Settings should be gray-out if they have read-only or simply not allowed to be visible if they don't have any permissions.
As Nic mentioned our colleagues the SysAdmins have the need to self manage the Agents and the policies. We(Security Team) we need to manage/(OS)query more or all. I usually do this from the Default Space.
Especially related to the latest metricbeat memory leak https://github.com/elastic/beats/issues/37142 that affected and annoyed a few of my windows admin colleagues. They requested to be able to self tune the policies and control the Agent.

**Comment by jlind23** [comment]
Closing this in favour of the issues below which are all space awareness related.
- [ ] https://github.com/elastic/kibana/issues/180708
- [ ] https://github.com/elastic/kibana/issues/181860
- [ ] https://github.com/elastic/kibana/issues/182717
- [ ] https://github.com/elastic/fleet-server/issues/3505
- [ ] https://github.com/elastic/kibana/issues/182817
- [ ] https://github.com/elastic/kibana/issues/172963
- [ ] https://github.com/elastic/kibana/issues/182735
- [ ] https://github.com/elastic/kibana/issues/182729
- [ ] https://github.com/elastic/kibana/issues/182733
- [ ] https://github.com/elastic/kibana/issues/182736
