### ISSUE TITLE
Support dynamically changing the Fleet server log level

### ISSUE THREAD

**Issue by cmacknz** [elastic/fleet-server#2186]
Follow up from an agent change in https://github.com/elastic/elastic-agent/issues/1896 where the agent will no longer restart itself or the processes it manages when the agent log level is changed.

Fleet server should respect the log level requested in the UnitExpected gRPC message by changing their log level dynamically when an update is received: https://github.com/elastic/elastic-agent-client/blob/15881a8e64ef95f32f688c933319cd926ff500b0/elastic-agent-client.proto#L280

```protobuf
    // Log level of the unit.
    UnitLogLevel log_level = 6;
```

**Comment by michel-laterman** [comment]
afaik the logger level should be changed when the reconfigure method is called for a fleet-server instance (the logger passed as a reloadable):
https://github.com/elastic/fleet-server/blob/9c8c9ee7519910276cced8d001ac5e8ab2f244e0/internal/pkg/server/agent.go#L308-L327
The reconfigure is called when unitModification is detected:
https://github.com/elastic/fleet-server/blob/9c8c9ee7519910276cced8d001ac5e8ab2f244e0/internal/pkg/server/agent.go#L201-L202

Is the issue here to use the log level (2nd ret val) of `state, _, _ := unit.Expected()` directly?

**Comment by cmacknz** [comment]
I haven't looked at the implementation in Fleet server, this was a tracking issue to make sure we made this change.

If this is already implemented and working as expected we can close this issue.

**Comment by michel-laterman** [comment]
From my testing the log level changes.
The action creates a new config with the log level chagne, the agent runner executes the `log.Reload` func, then more generic `configChangedServer` section executes
https://github.com/elastic/fleet-server/blob/9c8c9ee7519910276cced8d001ac5e8ab2f244e0/internal/pkg/server/fleet.go#L175-L184

I'm not sure if the `configChangedSever` restart is needed for a log level change but that may be investigated separately
