### ISSUE TITLE
[Question]: Fleet Server agent shows error logs when assigned from Default Fleet Server policy to Default Policy on self-managed Kibana.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#274]
**Description:**
Question ticket: Need to confirm fleet agent behavior on assigning new policy in a self managed stack.

Here, on 7.13 BC2 self managed stack, while doing some exploratory, we attempted to update Fleet Server Agent enrolled with Default Fleet Server Policy to Default Policy. After changing agent policy, we observed below errors under Logs tab.

**Error logs:**
`
elastic_agent
[elastic_agent][error] failed to dispatch actions, error: fail to generate program configuration: expecting Dict and received *transpiler.Key for '0'
`

**Build Details:**
```
Artifact link used: https://staging.elastic.co/7.13.0-24571870/summary-7.13.0.html
Build: 40598
Commit: a2f386b628764ea82af0893b8e25a16290dd6f44
```

Further, we have come up with below queries.
**Queries:**
- Could you please confirm expected behavior in above scenario as Default Fleet Server Policy is not managed in self managed stack?
- As we can install only single agent on self managed kibana, so how can we validate other integration such as System and Endpoint Security or any others.
- Is fleet agent restricted under Default Fleet Server Policy and not under any other policy?
- Can we update  Default Fleet Server Policy with new changes and integrations?

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigend to @EricDavisX

**Comment by EricDavisX** [comment]
to your Queries:

Could you please confirm expected behavior in above scenario as Default Fleet Server Policy is not managed in self managed stack?
Answer: If the policy is the 'Default Fleet Server policy' it can be changed, it is not intended to be locked like the policy on cloud.

As we can install only single agent on self managed kibana, so how can we validate other integration such as System and Endpoint Security or any others.
Answer: I don't fully understand why this would be the case.  Multiple Fleet Servers each with multiple Agents is the intention for support for self-managed stacks.  However, as noted above, you can update any policy on the self-managed stack to include whichever Integrations you wish.

Is fleet agent restricted under Default Fleet Server Policy and not under any other policy?
Answer: see above, it is not restricted on self-managed stacks.

Can we update Default Fleet Server Policy with new changes and integrations?
Answer yes, just like editing any other policy.

-------------
So to your original test scenario, it is interesting - it sounds like a good feature to ask Admins to double-confirm before removing the Fleet Server Integration from a policy, at least if there are any Agents on the policy in question.  @mostlyjason should we consider that feature work to do sometime?  

If nothing else bad happens and just an error in the logs, we can likely live with it unless someone already knows it is an easy and unimpactful change.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Thanks for the feedback. 
We are able to assign Fleet server agent to new policy. Further to remove the errors on reassigning policy, we found out that **Fleet Server integration must be added to the policy to which agent is assigned to**.

> I don't fully understand why this would be the case. Multiple Fleet Servers each with multiple Agents is the intention for support for self-managed stacks. 

Can you please give us detailed steps to enroll multiple fleet servers and elastic agents on self-managed kibana?
As we are unable to install second Fleet Server agent or secondary Elastic-agent on self managed kibana.
-  Please share entry required to put in Fleet Server host url for self managed kibana?
- How to connect to self managed kibana from other machines. (when elasticsearch url is http://localhost:9200)

We are unable to establish connection with Kibana from other machines.

Thanks
QAS

**Comment by mostlyjason** [comment]
This seems like kind of a weird edge case because I don't expect people to run a non-fleet server policy on a fleet agent often. Theoretically it could work, but I'm worried that agent will have too many permissions. I made a note to add a more clear error message here https://github.com/elastic/beats/issues/23753

**Comment by EricDavisX** [comment]
let's talk in our sync up @amolnater-qasource - here is a screenshot for ref on how to add multiple Fleet Servers to the system:
<img width="507" alt="Screen Shot 2021-04-27 at 4 35 12 PM" src="https://user-images.githubusercontent.com/12970373/116309334-a1f37a80-a776-11eb-9a7d-f444e8b47f6d.png">

**Comment by ph** [comment]
The original description from the translate key is fixed  by @michalpristas, can you link PR.
