### ISSUE TITLE
[Performance] Improve fleet server benchmarks

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#3152]
Thanks to https://github.com/elastic/fleet-server/pull/3141 we now have fleet server benchmarks running on every PR.
As of today this is not a blocking check as we found some flakiness in these benchmarks.

Looking at the comparison results [here](https://buildkite.com/elastic/fleet-server/builds/2661) and in the screenshot below, the performance difference is higher than the 10% threshold we defined. We need to understand why there is so much and fix the flakiness.
<img width="1178" alt="Screenshot 2023-12-07 at 14 13 17" src="https://github.com/elastic/fleet-server/assets/43535167/c24c0578-d96e-4b4b-9be1-31052d8ea2f4">

## Outcome

- [ ] The outcome of this issue is to make the benchmark run a blocker for the Buildkite pipeline

**Comment by jlind23** [comment]
@scunningham according to the git history you are the one who introduced these benchmarks a couple of years ago. Do you have any insights to share onto why we might see some performance discrepancies while testing the exact same code twice?

cc @alexsapran

**Comment by scunningham** [comment]
> @scunningham according to the git history you are the one who introduced these benchmarks a couple of years ago. Do you have any insights to share onto why we might see some performance discrepancies while testing the exact same code twice?
> 
> cc @alexsapran

Hard to say, much has changed in Fleet Server since I worked on it.  Would require some  investigation, but I'd be interested in network performance and error rates.  When I last tested, most of the performance issue were Elastic related, particularly in auth latency amongst others.

**Comment by alexsapran** [comment]
Another improvement we can do is the following, the BK annotation changes the status depending on the outcome of the step. 
In addition to the BK annotation, we could also post to the https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status with a context, `benchmarks` and have it `green|red`.

**Comment by michel-laterman** [comment]
There's an upstream issue for inconsistent benchmark results when the CPU numbers are pinned, https://github.com/golang/go/issues/31599, but I'm not sure if that effects us here.

While we have some benchmarks defined in `*_integration_test.go` files, I don't think they run or are part of the (failing) comparisons.

I'll try to make sure timers are reset before the benchmarks are ran in order to see if that cleans it up

**Comment by michel-laterman** [comment]
I think the errors may be caused by how `gobenchdata` analyses the benchmarks output.
The [1st test run](https://buildkite.com/elastic/fleet-server/builds/3278) shows a difference of over 13% for `github.com/elastic/fleet-server/v7/internal/pkg/checkin.BenchmarkBulk_1-8`.

However if I download the base and next artifacts and compare them with `benchstat` we see that takes all runs into account:
```
pkg: github.com/elastic/fleet-server/v7/internal/pkg/checkin
                   │  ./base.out  │             ./next.out             │
                   │    sec/op    │   sec/op     vs base               │
Bulk_1-8             71.19n ±  0%   71.02n ± 0%   -0.24% (p=0.003 n=8)
```

**Comment by jlind23** [comment]
> I think the errors may be caused by how gobenchdata analyses the benchmarks output.

Any solution that you believe would help us out?

**Comment by michel-laterman** [comment]
I've merged the PR to make the benchmarks more consistent (hopefully).
But I have not forced the PR to fail if the benchmarks detect an issue, i think there is a big difference between how `gobenchdata` and `benchstat` compares the results. 
I think [benchdiff](github.com/willabides/benchdiff) shows some promise as it uses benchstat to compare, but i have not looked into it too much
