### ISSUE TITLE
Bootstrapping of Elastic indices for Fleet / Fleet-Server, Phase 1

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#51]
Currently the bootstrapping of the fleet-server indices happens in fleet-server. This issue is to come to a conclusion on where the bootstrapping should happen (fleet-server, Elasticsearch, Kibana) for the first phase.

Related issues / PRs:

* System index plugin in Elasticsearch https://github.com/elastic/elasticsearch/issues/64971 https://github.com/elastic/elasticsearch/pull/65275

**Comment by aleksmaus** [comment]
Adding @nchaulet since probably he might end up handling that on Kibana side for the beta release upon the fleet enabling in the Kibana UI.

**Comment by scunningham** [comment]
@ruflin Objections to pushing this code into Kibana and dropping packages?  The packages don't seem to be buying us much here.  They are particularly problematic during upgrade scenarios, as it requires direct user interaction with privs to install the new packages.  So you end up in scenarios where Kibana is upgraded, but the Fleet code in Kibana cannot behave properly because it is dependent a package that is yet to, if ever, be installed.

Ideally, Kibana would pin, ship, and install dependent package on upgrade.  To my understanding, we are not there yet.

**Comment by scunningham** [comment]
To wit, we have the following dependencies:

mapping templates
ilm policy

those should be installed *before* creating the indices.

Looking into how system indices might help alleviate this issue.  It's not clear that ILM policy is related to system indices.

**Comment by ruflin** [comment]
@scunningham No objections to drop the package idea. The issue that will stay is around index template setup and permissions, would be good to solve it in ES for now.

**Comment by ruflin** [comment]
Closing this issue as https://github.com/elastic/kibana/pull/91543 got merged. @nchaulet Please let me know if there are parts missing for Phase 1.
