### ISSUE TITLE
Cleanup old actions

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#53]
Curently old actions are not cleaned up. Actions should be cleaned up automatically after a certain time (2 weeks?)

**Comment by ph** [comment]
@ruflin is this handled by this [ILM policy](https://github.com/elastic/integrations/blob/master/packages/fleet_server/elasticsearch/ilm_policy/.fleet-actions-results.json) or something more involved?  The 2 weeks case you are referencing is similar to a user taking two weeks of vacation. What happens when the laptop goes back online?

**Comment by ruflin** [comment]
Looks like this is solved by the policy. We should probably have a follow up discussion around the exact content of the policy. Closing this issue.
